$ANSIBLE_VAULT;1.1;AES256
38306233623262386536393131636264656462613061376265613130393862666236653730363463
3831666462613366396636633233343461303839363366650a346433363638386564303366326331
61636630323761366634336232646263643163643533663062383435363661313635653838383763
3561373731303632340a346462663734366463633539393235393630623436613832666563396232
64313664333466623564383936616365383833666337383662656665363562376135616537323361
62653232343832366135336131666362616562633037363436393265313830356437653832616563
623063663032613362303461373466663866
